version: '3'
services:
  web:
    image: nginx 
    build: 
      dockerfile: dockerfile
    ports: 
      - '80:80'
    links:
      - databaseA
    networks:
      - app-network
    depends_on:
      - databaseA
  databaseA:
    image: mysql 
    networks:
      - app-network
    build:
      dockerfile: docker-contextA/dockerfile.a
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filesA
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - dataA:/var/lib/mysql
      - ./createsA.sql:/docker-entrypoint-initdb.d/createsA.sql
#  databaseB:
#    image: mysql:latest 
#    build:
#      dockerfile: docker-contextB/dockerfile.b
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: password

#      MYSQL_ROOT_HOST: 'mysql'
#    ports:
#      - "3308:3306"
#    expose:
#      - 3306
#    volumes:
#      - dataB:/var/lib/mysql
#      - ./createsB.sql:/docker-entrypoint-initdb.d/createsB.sql

volumes:
  dataA:
    external: true
  dataB:
    external: true

networks:
  app-network:
    driver: bridge
      

      