version: '3'
services:
  #web:
   # image: nginx 
    #build: 
      #context: .
      #dockerfile: dockerfile
    #ports: 
     # - '8080:8080'
  databaseA:
    image: mysql:latest 
    build:
      context: .
      dockerfile: dockerfile.a
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filesA
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3309:3306'
    volumes:
      - dataA:/var/lib/mysql
      - ./createsA.sql:/docker-entrypoint-initdb.d/createsA.sql
  databaseB:
    image: mysql:latest 
    build:
      context: .
      dockerfile: dockerfile.b
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filesB
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - dataB:/var/lib/mysql
      - ./createsB.sql:/docker-entrypoint-initdb.d/createsB.sql

volumes:
  dataA:
    external: true
  dataB:
    external: true

      