services:
  web:
    image: nginx:latest
    build: .
    ports: 
      - '8080:8080'
    networks:
      - file-saving-network
  databaseA:
    image: mysql:latest 
    build: ./mysqlBuildA
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filesA
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./createsA.sql:/docker-entrypoint-initdb.d/createsA.sql
    networks:
      - file-saving-network
  databaseB:
    image: mysql:latest 
    build: ./mysqlBuildB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: filesB
    #ports:
      #- "3306:3306"
    #expose:
      #- '3306'
    volumes:
      - ./createsB.sql:/docker-entrypoint-initdb.d/createsB.sql
    networks:
      - file-saving-network
networks:

  file-saving-network: {}

